services:
  painters-server:
    build:
      context: .  # Use the current directory as the build context
      dockerfile: Dockerfile  # The Dockerfile to use for building the image
    container_name: painters-server-container
    # ports:
    #   - "80:80"
    volumes:
      - ./maps:/app/maps  # Mount the local maps directory to the container
    restart: unless-stopped  # Automatically restart the container unless stopped manually
    networks:
      - my_network

networks:
  my_network:
    external: true